//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaHut.Domain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaHutDbEntities : DbContext
    {
        public PizzaHutDbEntities()
            : base("name=PizzaHutDbEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cartItem> cartItem { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<pizzas> pizzas { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
